name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]
  # เพิ่ม release event
  release:
    types: [published, created]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job for documentation/static site
  build-docs:
    runs-on: ubuntu-latest
    # ปรับเงื่อนไขให้รันทั้งเมื่อ push และเมื่อ release จาก production
    # (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production')) ||
    if: |
        (github.event_name == 'release' && github.event.release.target_commitish == 'production')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # สำคัญ: checkout จาก branch ไม่ใช่ tag
          ref: ${{ github.event.release.target_commitish || github.ref }}
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          
      - name: Generate documentation
        run: |
          # สร้าง documentation จาก Flask app
          mkdir -p docs/_static
          mkdir -p docs/_templates
          
          # สร้างหน้า index.html สำหรับ documentation
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="th">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>TeamUp Calendar - Dialysis Scheduler</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
              <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
              <style>
                  .feature-card {
                      transition: transform 0.2s;
                      border: none;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                  }
                  .feature-card:hover {
                      transform: translateY(-5px);
                      box-shadow: 0 4px 8px rgba(0,0,0,0.15);
                  }
                  .hero-section {
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      padding: 4rem 0;
                      margin-bottom: 3rem;
                  }
                  .tech-badge {
                      display: inline-block;
                      padding: 0.5rem 1rem;
                      background: #f8f9fa;
                      color: #495057;
                      border-radius: 20px;
                      margin: 0.25rem;
                      font-size: 0.9rem;
                  }
              </style>
          </head>
          <body>
              <!-- Hero Section -->
              <div class="hero-section">
                  <div class="container">
                      <div class="row justify-content-center text-center">
                          <div class="col-md-8">
                              <h1 class="display-4 mb-4">
                                  <i class="fas fa-calendar-alt me-3"></i>
                                  TeamUp Calendar
                              </h1>
                              <p class="lead mb-4">ระบบจัดการตารางนัดหมายฟอกไตที่ทันสมัย</p>
                              <p class="mb-0">เชื่อมต่อกับ TeamUp Calendar API เพื่อการจัดการที่มีประสิทธิภาพ</p>
                          </div>
                      </div>
                  </div>
              </div>
              
              <div class="container">
                  <!-- Features Section -->
                  <div class="row mb-5">
                      <div class="col-12 text-center mb-4">
                          <h2 class="h1">คุณสมบัติของระบบ</h2>
                          <p class="text-muted">ระบบที่ครบครันสำหรับการจัดการนัดหมายฟอกไต</p>
                      </div>
                  </div>
                  
                  <div class="row g-4 mb-5">
                      <div class="col-md-6 col-lg-4">
                          <div class="card feature-card h-100">
                              <div class="card-body text-center">
                                  <i class="fas fa-plus-circle text-success fs-1 mb-3"></i>
                                  <h5 class="card-title">สร้างนัดหมายใหม่</h5>
                                  <p class="card-text">สร้างนัดหมายฟอกไตใหม่ได้อย่างง่ายดาย พร้อมข้อมูลครบถ้วน</p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-6 col-lg-4">
                          <div class="card feature-card h-100">
                              <div class="card-body text-center">
                                  <i class="fas fa-calendar-check text-info fs-1 mb-3"></i>
                                  <h5 class="card-title">ดูรายการนัดหมาย</h5>
                                  <p class="card-text">ดูรายการนัดหมายตามวันที่ พร้อมการกรองและค้นหา</p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-6 col-lg-4">
                          <div class="card feature-card h-100">
                              <div class="card-body text-center">
                                  <i class="fas fa-edit text-warning fs-1 mb-3"></i>
                                  <h5 class="card-title">อัปเดตสถานะ</h5>
                                  <p class="card-text">อัปเดตสถานะการนัดหมาย มาตามนัด ยกเลิก หรือไม่มา</p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-6 col-lg-4">
                          <div class="card feature-card h-100">
                              <div class="card-body text-center">
                                  <i class="fas fa-file-import text-primary fs-1 mb-3"></i>
                                  <h5 class="card-title">นำเข้าจาก CSV</h5>
                                  <p class="card-text">นำเข้าข้อมูลจากไฟล์ CSV ได้อย่างรวดเร็ว</p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-6 col-lg-4">
                          <div class="card feature-card h-100">
                              <div class="card-body text-center">
                                  <i class="fas fa-repeat text-secondary fs-1 mb-3"></i>
                                  <h5 class="card-title">นัดหมายซ้ำ</h5>
                                  <p class="card-text">สร้างนัดหมายซ้ำแบบอัตโนมัติตามรูปแบบที่กำหนด</p>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-6 col-lg-4">
                          <div class="card feature-card h-100">
                              <div class="card-body text-center">
                                  <i class="fas fa-search text-dark fs-1 mb-3"></i>
                                  <h5 class="card-title">ค้นหาและกรอง</h5>
                                  <p class="card-text">ค้นหาและกรองนัดหมายได้อย่างมีประสิทธิภาพ</p>
                              </div>
                          </div>
                      </div>
                  </div>
                  
                  <!-- Technology Stack -->
                  <div class="row mb-5">
                      <div class="col-12 text-center mb-4">
                          <h2>เทคโนโลยีที่ใช้</h2>
                      </div>
                      <div class="col-12 text-center">
                          <span class="tech-badge"><i class="fab fa-python me-2"></i>Python Flask</span>
                          <span class="tech-badge"><i class="fab fa-js-square me-2"></i>JavaScript</span>
                          <span class="tech-badge"><i class="fab fa-bootstrap me-2"></i>Bootstrap 5</span>
                          <span class="tech-badge"><i class="fas fa-database me-2"></i>TeamUp API</span>
                          <span class="tech-badge"><i class="fas fa-file-csv me-2"></i>CSV Support</span>
                          <span class="tech-badge"><i class="fab fa-github me-2"></i>GitHub Actions</span>
                      </div>
                  </div>
                  
                  <!-- Getting Started -->
                  <div class="row mb-5">
                      <div class="col-md-6">
                          <div class="card">
                              <div class="card-body">
                                  <h5 class="card-title">
                                      <i class="fas fa-download text-primary me-2"></i>
                                      การติดตั้ง
                                  </h5>
                                  <p class="card-text">Clone repository และติดตั้ง dependencies</p>
                                  <div class="bg-light p-3 rounded">
                                      <code>git clone &lt;repository-url&gt;</code><br>
                                      <code>pip install -r requirements.txt</code><br>
                                      <code>python app.py</code>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-6">
                          <div class="card">
                              <div class="card-body">
                                  <h5 class="card-title">
                                      <i class="fas fa-cog text-success me-2"></i>
                                      การใช้งาน
                                  </h5>
                                  <p class="card-text">ตั้งค่า TeamUp API และเริ่มใช้งาน</p>
                                  <div class="bg-light p-3 rounded">
                                      <code>1. ตั้งค่า API Key</code><br>
                                      <code>2. เชื่อมต่อ Calendar</code><br>
                                      <code>3. เริ่มใช้งาน</code>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  
                  <!-- Links -->
                  <div class="row mb-5">
                      <div class="col-12">
                          <div class="card">
                              <div class="card-body text-center">
                                  <h5 class="card-title mb-4">ลิงค์ที่เกี่ยวข้อง</h5>
                                  <div class="d-flex justify-content-center gap-3 flex-wrap">
                                      <a href="https://github.com/your-username/your-repo" class="btn btn-outline-primary">
                                          <i class="fab fa-github me-2"></i>GitHub Repository
                                      </a>
                                      <a href="https://teamup.com" class="btn btn-outline-success">
                                          <i class="fas fa-calendar me-2"></i>TeamUp Calendar
                                      </a>
                                      <a href="https://flask.palletsprojects.com/" class="btn btn-outline-info">
                                          <i class="fas fa-book me-2"></i>Flask Documentation
                                      </a>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              
              <!-- Footer -->
              <footer class="bg-light py-4 mt-5">
                  <div class="container text-center">
                      <p class="mb-0 text-muted">
                          <i class="fas fa-heart text-danger me-2"></i>
                          สร้างด้วย Flask และ TeamUp Calendar API
                      </p>
                  </div>
              </footer>
              
              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
          EOF
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  # Deployment job - รันเฉพาะเมื่อมี release จาก production branch
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    # Deploy เฉพาะเมื่อเป็น release event จาก production branch
    if: ${{ github.event_name == 'release' && github.event.release.target_commitish == 'production' }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4